### ISSUE TITLE
Pass name of backend to angular via environment variable

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-integral#1]
Currently, when launched via Docker Compose, the frontend still points to `ngrok.luozm.me:8395` as the backend rather than pointing to the `ccvg` container.

This appears to be hardcoded in ccvgd-frontend here:
https://github.com/ulsdevteam/ccvgd-frontend/blob/be07f3ddaa9b0a1e33d64edb3eea506f36554640/src/environments/environment.prod.ts#L4
and
https://github.com/ulsdevteam/ccvgd-frontend/blob/be07f3ddaa9b0a1e33d64edb3eea506f36554640/src/environments/environment.ts#L7

Instead, these configurations should receive the desired endpoint name as an environment variable, which can be set when building the ccvgd-frontend repo directly, but can also be passed in from docker compose by the integral repo.

**Comment by Caligula1022** [comment]
I finally solved this problem after looking up a lot of documents.

**Comment by Caligula1022** [comment]
Since I've recently tested positive for covid19, updates on several other issues may take a little longer. I'm sorry about that.

**Comment by ctgraham** [comment]
I hope that you are feeling better soon!  I will test your changes and provide some feedback.

**Comment by ctgraham** [comment]
@Caligula1022 , I have added two PRs for your review which should help give some guidance on this issue.
 - https://github.com/ulsdevteam/ccvgd-integral/pull/5
 - https://github.com/ulsdevteam/ccvgd-frontend/pull/32

**Comment by Caligula1022** [comment]
Hello Clinton,

Thank you so much for your help!

My covid-19 test is now negative, and I feel much better.

I'm working on these issues as a faster pace.

Thanks again for your guidance, I think it helped a lot.

Kind regards,

Yifei Tai

From: Clinton Graham ***@***.***>
Date: Wednesday, September 14, 2022 at 2:31 PM
To: ulsdevteam/ccvgd-integral ***@***.***>
Cc: Yifei Tai ***@***.***>, Mention ***@***.***>
Subject: Re: [ulsdevteam/ccvgd-integral] Pass name of backend to angular via environment variable (Issue #1)

@Caligula1022<https://github.com/Caligula1022> , I have added two PRs for your review which should help give some guidance on this issue.
