### ISSUE TITLE
Redact credentials

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-integral#3]
Migrated from: https://github.com/Caligula1022/ccvg_integral/issues/3

We will also want to redact the existing use of hardcoded credentials ([specifically, the database credentials](https://github.com/ulsdevteam/ccvgd-integral/blob/dae9c2993059c0a6ba2c4d81187b8e101e288821/docker-compose.yml#L28-L29)) to allow these credentials to be managed via an [untracked environment file](https://docs.docker.com/compose/env-file/).

These credentials should be pass from this repo's docker-compose to the backend's docker build, so that changing the values in the environment for docker-compose here is inherited by the backend build, and credentials do not need to be reiterated in that repo.

As a best practice, you should:

- Provide a copy of a sample environment file which is committed to the repo
- Add the actual environment file referenced in the docker compose file to the .gitignore
- Provide instructions in the README for the user to copy the sample file to the actual filename, modifying the values to their own settings.

This way, there is no risk of the user accidentally committing their secrets to the git repository.

**Comment by Caligula1022** [comment]
This one is done, you can check.

**Comment by ctgraham** [comment]
Note that even though `env_file` was added to the .gitignore:
https://github.com/ulsdevteam/ccvgd-integral/blob/5a0329b0e898939312f49e6ecaf8403965a538e5/.gitignore#L1
It still exists in the repo:
https://github.com/ulsdevteam/ccvgd-integral/blob/5a0329b0e898939312f49e6ecaf8403965a538e5/env_file#L1-L6

Two takeaways from this:

1. Be sure to `git rm` a file you have added to .gitignore, if you had previously committed it.
2. Anything committed to git is committed forever, so even if you .gitignore and `git rm` a file, you should still consider the content public.

The PR for https://github.com/ulsdevteam/ccvgd-integral/pull/5 illustrates a commit for removing the env_file and adding an untracked .env file.

**Comment by Caligula1022** [comment]
It's done. **git rm** is good.
