### ISSUE TITLE
Clean build of backend doesn't automatically load the data

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-integral#6]
With an initial build of the ccvgd-backend container, nothing automatically triggers a data load via the [python scripts](https://github.com/ulsdevteam/ccvgd-backend/tree/cvgd-backend/externalFile/pythonScript).

This should either be automated in the Dockerfile / docker-compose, or should be documented in the READMEs to indicate how do do the initial data load in a containerized environment.

**Comment by Caligula1022** [comment]
I'm not so sure. The general case is that the backend container is started only after the db container is started, and the db container automatically imports the sql file stored in the db folder as initialization.

**Comment by ctgraham** [comment]
Confirmed.  The database is being build on initial container creation via the [docker-entrypoint-initdb.d](https://github.com/ulsdevteam/ccvgd-integral/blob/5a0329b0e898939312f49e6ecaf8403965a538e5/docker-compose.yml#L30).  Nothing to fix here.
